apiVersion: v1
kind: Namespace
metadata:
  name: flask
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      namespace: flask
      labels:
        app: flask-app
    spec:
      containers:
      - name: discoverdollarrepo
        image: githubactionacrprac.azurecr.io/flask:${{ github.sha }}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-svc
  namespace: flask
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
